GET http://localhost:3000/api/wallets/b3537a8ddb5ad5ef6d1899111a85fd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dGVzdCIsImlhdCI6MTYzNTkwMDEyMTMyOCwiZXhwIjoxNjM1OTg2NTIxMzI4fQ.VhPL1NWZH4sPwLdQdB5-VgOLRClhUfj-12JnlD554Ys
