GET http://localhost:3000/api/addresses/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dGVzdCIsImlhdCI6MTYzNjExNjkwMjExNSwiZXhwIjoxNjM2MjAzMzAyMTE1fQ.cHAt_Ti_C_s7lBEtI0fiBQdAMrSO6pbzCilTtPTlK9w
