GET http://localhost:3000/api/wallets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dGVzdCIsImlhdCI6MTYzNjE4ODM0NjE3OCwiZXhwIjoxNjM2Mjc0NzQ2MTc4fQ.VwgM5iJfPK0ZFfmD0HTdkM4Dz8U2_4vPfHXCEe7pTY4
